# ── Exam tables ───────────────────────────────────────────────
# Self-migrating, same pattern routes/decks.py's _ensure_deck_schema
# uses. A generated paper is materialized once per (exam_id, revision)
# in exam_papers rather than regenerated per request: getExam() is called independently by
# ExamRunner, by ExamResult on the reload path, and again inside
# submitAttempt to score — a generate-on-every-call design would grade
# a learner's answers against a different paper than they took. Attempts
# (exam_attempts) are persisted so the result screen survives a reload
# instead of depending only on React Router's in-memory location.state.
#
# ── Revisions ────────────────────────────────────────────────
# A paper used to be one row per exam_id, forever. Two things that
# breaks, both real:
#
#   - a learner who has already sat n5-reading-01 is served the same
#     paper every time afterwards, which tests recall of the answers
#     rather than the language;
#   - a paper generated by a prompt that has since been fixed can never
#     be retired, because the row is the only one there is.
#
# So papers are keyed (exam_id, revision) and the pool is SHARED: any
# learner may be served any revision. routes/exams.py picks the lowest
# revision of the current generator_version that THIS user has not
# attempted, and only pays for a new revision when there is none left
# for them. One learner's generation cost therefore benefits everyone
# who comes after -- which is the whole reason papers are global rather
# than per-user in the first place.
#
# generator_version is what retires a bad paper: bumping it in
# routes/exams.py's EXAM_GENERATORS makes every older revision
# unservable at once, without deleting anything, so past attempts still
# render against the paper they were actually taken on.
from core.db import db_conn


def ensure_exam_schema() -> None:
    conn = db_conn()
    try:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS exam_papers (
                    exam_id           TEXT NOT NULL,
                    revision          INT NOT NULL DEFAULT 1,
                    level             TEXT NOT NULL,
                    seed              BIGINT NOT NULL,
                    generator_version TEXT NOT NULL,
                    paper             JSONB NOT NULL,
                    section_count     INTEGER NOT NULL,
                    question_count    INTEGER NOT NULL,
                    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    PRIMARY KEY (exam_id, revision)
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS exam_attempts (
                    id          BIGSERIAL PRIMARY KEY,
                    user_id     TEXT NOT NULL,
                    exam_id     TEXT NOT NULL,
                    revision    INT NOT NULL DEFAULT 1,
                    section_id  TEXT NOT NULL,
                    answers     JSONB NOT NULL,
                    review      JSONB NOT NULL,
                    per_section JSONB NOT NULL,
                    correct     INTEGER NOT NULL,
                    total       INTEGER NOT NULL,
                    started_at  TIMESTAMPTZ NOT NULL,
                    finished_at TIMESTAMPTZ NOT NULL,
                    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    CONSTRAINT exam_attempts_paper_fkey
                        FOREIGN KEY (exam_id, revision)
                        REFERENCES exam_papers(exam_id, revision)
                )
            """)
            cur.execute("""
                CREATE INDEX IF NOT EXISTS idx_exam_attempts_user
                ON exam_attempts(user_id, created_at DESC)
            """)
            # One row per exam id currently being generated, or whose
            # last generation failed. There is deliberately no 'done'
            # status: the row is DELETED on success, and the exam_papers
            # row above is what "done" means.
            #
            # The primary key is the lock. Generating an LLM-backed paper
            # takes minutes and dozens of model calls, and it used to run
            # synchronously inside the request handler with nothing
            # stopping a second request -- a refresh, a second tab, or
            # the retry button on the failure screen -- from starting the
            # whole cascade again alongside the first. An INSERT ...
            # ON CONFLICT DO NOTHING here means exactly one caller can
            # claim an exam id; everyone else reads the row and waits.
            #
            # A failed row is kept (not deleted) precisely so a retry
            # within the cooldown can be answered instantly, without
            # re-paying for a failure whose cause -- no API key, provider
            # outage, a model that can't hold the format -- will not have
            # changed in the meantime.
            cur.execute("""
                CREATE TABLE IF NOT EXISTS exam_generation_jobs (
                    exam_id    TEXT PRIMARY KEY,
                    revision   INT NOT NULL DEFAULT 1,
                    status     TEXT NOT NULL,
                    error      TEXT,
                    retry_after TIMESTAMPTZ,
                    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
            """)
            _migrate_to_revisions(cur)
        conn.commit()
    finally:
        conn.close()


# ── Revision migration ───────────────────────────────────────
# Idempotent, and safe on a database that already holds papers and
# attempts: every existing row defaults to revision 1, which is exactly
# the row it already pointed at, so nothing has to be rewritten.
#
# The primary key on exam_papers has to be replaced rather than added
# to, and exam_attempts' foreign key has to be dropped first because it
# depends on that key. Both are guarded on the CURRENT shape rather than
# on a version counter -- a fresh database reaches the target shape via
# the CREATE TABLEs above and skips straight past all of this.
def _migrate_to_revisions(cur) -> None:
    cur.execute("ALTER TABLE exam_papers   ADD COLUMN IF NOT EXISTS revision INT NOT NULL DEFAULT 1")
    cur.execute("ALTER TABLE exam_attempts ADD COLUMN IF NOT EXISTS revision INT NOT NULL DEFAULT 1")
    # The job row carries the revision its worker is generating, but the
    # PRIMARY KEY stays on exam_id alone: one generation in flight per
    # exam id is the credit guard this table exists for (see its comment
    # above), and allowing two revisions of one paper to generate
    # concurrently would quietly double the cost of the thing the lock
    # was introduced to stop.
    cur.execute("ALTER TABLE exam_generation_jobs ADD COLUMN IF NOT EXISTS revision INT NOT NULL DEFAULT 1")

    cur.execute("""
        SELECT 1 FROM pg_constraint
         WHERE conrelid = 'exam_attempts'::regclass AND contype = 'f'
           AND conname = 'exam_attempts_exam_id_fkey'
    """)
    if cur.fetchone():
        cur.execute("ALTER TABLE exam_attempts DROP CONSTRAINT exam_attempts_exam_id_fkey")

    # Is exam_papers' primary key still the single exam_id column?
    cur.execute("""
        SELECT COUNT(*) FROM pg_constraint
         WHERE conrelid = 'exam_papers'::regclass AND contype = 'p'
           AND array_length(conkey, 1) = 1
    """)
    if cur.fetchone()[0]:
        cur.execute("ALTER TABLE exam_papers DROP CONSTRAINT exam_papers_pkey")
        cur.execute("ALTER TABLE exam_papers ADD PRIMARY KEY (exam_id, revision)")

    # After the ALTERs above, not beside the other CREATE INDEX: on a
    # database that predates revisions the column does not exist yet
    # when the table statements run. Covers the "has this user already
    # sat this revision?" NOT EXISTS in routes/exams.py's paper
    # selection, which runs once per catalog entry on every visit to the
    # picker screen (20 entries) and again on every exam open.
    cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_exam_attempts_paper
        ON exam_attempts(exam_id, revision, user_id)
    """)

    cur.execute("""
        SELECT 1 FROM pg_constraint
         WHERE conrelid = 'exam_attempts'::regclass AND contype = 'f'
           AND conname = 'exam_attempts_paper_fkey'
    """)
    if not cur.fetchone():
        cur.execute("""
            ALTER TABLE exam_attempts
              ADD CONSTRAINT exam_attempts_paper_fkey
              FOREIGN KEY (exam_id, revision) REFERENCES exam_papers(exam_id, revision)
        """)
