# ── 実力診断 — the onboarding placement test ──────────────────────
# Twelve deterministic questions laddering N5→N1, built entirely from
# data this project already owns and scored by study/exam_scoring.py's
# pure functions. No LLM, no network, no database: a paper builds in
# milliseconds, which is the whole reason this module exists instead of
# a 21st entry in routes/exams.py's EXAM_GENERATORS — that pipeline's
# papers are one-level, globally immutable, FK'd by attempts, and
# generated by an LLM behind a claim-lock job table that answers 202
# until a background thread finishes. Minutes of "generating…" is a
# fatal first-run experience; placement answers synchronously.
#
# Statelessness is the design: POST /placement returns {seed,
# questions-without-answers}; POST /placement/score regenerates the
# byte-identical paper FROM that seed and grades against it. Nothing is
# stored, nothing expires, and a tampered seed only mis-places the
# tamperer. That contract holds because everything here is a pure
# function of (seed, import-time content data) — keep it that way. In
# particular study/mcq.py's pick_distractors is deliberately NOT used:
# it draws from the module-global `random`, which would make the
# score-time regeneration disagree with the paper the learner saw.
import random

from content.grammar_points_data import GRAMMAR_POINTS_BY_LEVEL
from content.grammar_sentences_data import get_sentences
from content.vocab_data import VOCAB_BY_LEVEL
from study.difficulty import LEVELS
from study.exam_gen_utils import GenerationFailed, make_choices
from study.exam_kanji_gen import build_orthography_mondai, build_reading_mondai
from study.exam_vocab_gen import build_vocab_context_mondai
from study.grammar_match import contains_pattern, verifiable

# One entry per level, easiest first; the kinds are the question mix for
# that level's section. 3+3+2+2+2 = 12 questions. The lower levels get
# the extra item because that is where one question changes the
# recommendation the most (nearly every learner passes through them).
PLACEMENT_LADDER: list[tuple[str, list[str]]] = [
    ("N5", ["reading", "context", "grammar"]),
    ("N4", ["reading", "orthography", "grammar"]),
    ("N3", ["reading", "context"]),
    ("N2", ["orthography", "grammar"]),
    ("N1", ["reading", "context"]),
]

# A level is cleared at two thirds correct. recommend_level() walks the
# ladder and recommends the level AFTER the highest consecutively
# cleared one: you board where there is still something to learn.
_CLEAR_NUM, _CLEAR_DEN = 2, 3

_GRAMMAR_INSTRUCTIONS_JP = "つぎの　文で　つかわれている　文法を　1・2・3・4から　一つ　えらんで　ください。"


def _build_grammar_fill_mondai(spec: dict, level: str, rng: random.Random) -> dict:
    """One 'which rule is at work' item, the same shape routes/grammar.py's
    fill_in mode asks (the sentence shown INTACT — blanking the rule out
    has no unique answer, see grammar.py). Distractors are other
    verifiable same-level patterns that do NOT also appear in the
    sentence, so the item never has two defensible answers."""
    points = [
        g for g in GRAMMAR_POINTS_BY_LEVEL.get(level, [])
        if verifiable(g["pattern"]) and get_sentences(level, g["pattern"])
    ]
    for entry in rng.sample(points, len(points)):
        pattern = entry["pattern"]
        sentence = get_sentences(level, pattern)[0]
        others = [
            g["pattern"] for g in GRAMMAR_POINTS_BY_LEVEL[level]
            if g["pattern"] != pattern
            and verifiable(g["pattern"])
            and not contains_pattern(sentence["jp"], g["pattern"])
        ]
        made = make_choices(rng, pattern, others)
        if made is None:
            continue
        choices, answer_id = made
        return {
            "id": spec["id"],
            "number": spec["official_number"],
            "type": "mcq-text",
            "instructionsJp": _GRAMMAR_INSTRUCTIONS_JP,
            "instructions": "Choose the grammar pattern used in the sentence.",
            "questions": [{
                "id": f"{spec['id']}_q1",
                "number": 1,
                "promptJp": sentence["jp"],
                "choices": choices,
                "answer": answer_id,
            }],
        }
    raise GenerationFailed(f"{spec['id']}: no grammar point with a usable sentence at {level}")


def _build_one(kind: str, level: str, spec: dict, pool: list[dict],
               used_words: set, used_prompts: set, rng: random.Random) -> dict:
    if kind == "reading":
        return build_reading_mondai(spec, pool, used_words, used_prompts, rng)
    if kind == "orthography":
        return build_orthography_mondai(spec, pool, used_words, used_prompts, rng)
    if kind == "context":
        return build_vocab_context_mondai(spec, pool, used_words, used_prompts, rng, level)
    if kind == "grammar":
        return _build_grammar_fill_mondai(spec, level, rng)
    raise GenerationFailed(f"unknown placement kind {kind!r}")


def build_placement_paper(seed: int) -> dict:
    """The full 12-question paper, score_attempt-compatible. One section
    PER LEVEL (id 'N5'..'N1') — that structural choice is what makes
    score_attempt's perSection a per-level scoreboard with no changes to
    exam_scoring.py at all.

    Every (level, kind) build gets a fallback chain [kind, reading,
    orthography]: a placement must never fail because one word lacked a
    kanji-gated example sentence, and 'reading' over a full level pool
    practically cannot fail. The chain is itself replayed identically at
    score time — a failed builder is a pure function of the same seed
    and the same content data, so it fails the same way again."""
    rng = random.Random(seed)
    used_words: set = set()
    used_prompts: set = set()
    pools = {
        level: rng.sample(VOCAB_BY_LEVEL[level], len(VOCAB_BY_LEVEL[level]))
        for level, _ in PLACEMENT_LADDER
    }

    sections = []
    number = 0
    for level, kinds in PLACEMENT_LADDER:
        mondai = []
        for kind in kinds:
            number += 1
            built = None
            for attempt in (kind, "reading", "orthography"):
                spec = {"id": f"pl_{level}_{attempt}_{number}", "official_number": number, "count": 1}
                try:
                    built = _build_one(attempt, level, spec, pools[level], used_words, used_prompts, rng)
                    actual_kind = attempt
                    break
                except GenerationFailed:
                    continue
            if built is None:
                raise GenerationFailed(f"placement: every builder failed for {level}/{kind}")
            # The kind rides on each QUESTION (not the mondai) because
            # flatten_questions only carries a fixed set of mondai
            # fields through — and the frontend keys its per-kind
            # instruction line off this.
            for q in built["questions"]:
                q["kind"] = actual_kind
            mondai.append(built)
        sections.append({"id": level, "label": level, "mondai": mondai})

    return {"sections": sections}


def strip_answers(flat_questions: list[dict]) -> list[dict]:
    """What the client may see: everything but the answer key."""
    return [{k: v for k, v in q.items() if k != "answer"} for q in flat_questions]


def recommend_level(per_section: dict) -> str:
    """perSection (from score_attempt, keyed by level) → the boarding
    station. Unanswered questions are simply wrong — which is what makes
    a partial submission ('stop here, this is too hard') legal with no
    server-side session state."""
    cleared_up_to = None
    for level in LEVELS:
        stats = per_section.get(level) or {}
        total = stats.get("total", 0)
        correct = stats.get("correct", 0)
        if total and correct * _CLEAR_DEN >= total * _CLEAR_NUM:
            cleared_up_to = level
        else:
            break
    if cleared_up_to is None:
        return LEVELS[0]
    return LEVELS[min(LEVELS.index(cleared_up_to) + 1, len(LEVELS) - 1)]
