"""
What a radical MEANS — the half of the radical layer KANJIDIC2 does not
carry (plan 086).

datas/kanji/radicals.json knows the 214 by number, glyph and stroke
count, and which of them each kanji is filed under. It does not know
that 85 is water, that a learner will meet it as 氵 on the left of 海
and 泳 and 洗 far more often than as 水, or that its Japanese name in
that position is さんずい. This table is that knowledge, written by hand
once, in the two languages the app speaks plus the Japanese names the
learner will hear from every teacher and see in every 漢和辞典.

One row per Kangxi number:

    number: (meaning_en, meaning_fr, names_ja, forms, position)

    names_ja  the 部首名, commonest first. Where a radical is named
              differently by where it sits (ひ / ひへん, みず / さんずい)
              the standalone name leads and the positional ones follow.
    forms     the glyph as the learner MEETS it first, then the others:
              the compact component form leads where that is what the
              course's kanji actually show (氵 before 水 would be wrong
              — 水 is itself an N5 kanji — but 艹 before 艸 is right,
              because 艸 appears in nothing the course teaches). The
              first form is the glyph the study screens print large.
    position  where the component usually sits in a kanji, as one of
              POSITIONS' keys, or None when it has no usual place (most
              of the rare ones, and every radical that is mostly met as
              a whole kanji). The lesson turns it into a sentence; the
              frontend owns the wording.

The forms here are display forms, not the index's key: radicals.json's
`char` stays the identity the dictionary browses by and the radical
study mode grades against. See radical_data.info_for() for the merge.
"""

# The seven places a component takes in a character, by their
# traditional names. Keys are what the API sends; the frontend prints
# the Japanese and the plain-language word.
POSITIONS = ("hen", "tsukuri", "kanmuri", "ashi", "kamae", "tare", "nyou")

RADICAL_INFO: dict[int, tuple[str, str, tuple[str, ...], tuple[str, ...], str | None]] = {
    1:   ("one", "un", ("いち",), ("一",), None),
    2:   ("line", "trait vertical", ("ぼう", "たてぼう"), ("丨",), None),
    3:   ("dot", "point", ("てん",), ("丶",), None),
    4:   ("slash", "trait oblique", ("の", "はらいぼう"), ("丿",), None),
    5:   ("second, hook", "second, crochet", ("おつ", "おつにょう"), ("乙", "乚"), None),
    6:   ("hook", "crochet", ("はねぼう",), ("亅",), None),
    7:   ("two", "deux", ("に",), ("二",), None),
    8:   ("lid", "couvercle", ("なべぶた", "けいさんかんむり"), ("亠",), "kanmuri"),
    9:   ("person", "personne", ("ひと", "にんべん", "ひとやね"), ("人", "亻", "𠆢"), "hen"),
    10:  ("legs", "jambes", ("ひとあし", "にんにょう"), ("儿",), "ashi"),
    11:  ("enter", "entrer", ("いる", "いりがしら"), ("入",), None),
    12:  ("eight", "huit", ("はち", "はちがしら"), ("八",), None),
    13:  ("open frame", "cadre ouvert", ("けいがまえ", "どうがまえ"), ("冂",), "kamae"),
    14:  ("cover", "couvercle", ("わかんむり",), ("冖",), "kanmuri"),
    15:  ("ice", "glace", ("にすい",), ("冫",), "hen"),
    16:  ("table", "table", ("つくえ", "きにょう"), ("几",), None),
    17:  ("open box", "boîte ouverte", ("うけばこ", "かんにょう"), ("凵",), None),
    18:  ("knife", "couteau", ("かたな", "りっとう"), ("刀", "刂"), "tsukuri"),
    19:  ("power", "force", ("ちから",), ("力",), None),
    20:  ("wrap", "envelopper", ("つつみがまえ",), ("勹",), "kamae"),
    21:  ("spoon", "cuillère", ("さじ", "さじのひ"), ("匕",), None),
    22:  ("box", "boîte", ("はこがまえ",), ("匚",), "kamae"),
    23:  ("hiding place", "cachette", ("かくしがまえ",), ("匸",), "kamae"),
    24:  ("ten", "dix", ("じゅう",), ("十",), None),
    25:  ("divination", "divination", ("ぼく", "うらない"), ("卜",), None),
    26:  ("seal", "sceau", ("ふしづくり", "わりふ"), ("卩",), "tsukuri"),
    27:  ("cliff", "falaise", ("がんだれ",), ("厂",), "tare"),
    28:  ("private", "privé", ("む",), ("厶",), None),
    29:  ("right hand, again", "main droite, encore", ("また",), ("又",), None),
    30:  ("mouth", "bouche", ("くち", "くちへん"), ("口",), "hen"),
    31:  ("enclosure", "enceinte", ("くにがまえ",), ("囗",), "kamae"),
    32:  ("earth", "terre", ("つち", "つちへん"), ("土",), "hen"),
    33:  ("scholar", "lettré", ("さむらい",), ("士",), None),
    34:  ("go", "marcher", ("ふゆがしら", "のまた"), ("夂",), None),
    35:  ("go slowly", "marcher lentement", ("すいにょう",), ("夊",), None),
    36:  ("evening", "soir", ("ゆうべ", "た"), ("夕",), None),
    37:  ("big", "grand", ("だい",), ("大",), None),
    38:  ("woman", "femme", ("おんな", "おんなへん"), ("女",), "hen"),
    39:  ("child", "enfant", ("こ", "こへん"), ("子",), "hen"),
    40:  ("roof", "toit", ("うかんむり",), ("宀",), "kanmuri"),
    41:  ("inch", "pouce", ("すん",), ("寸",), None),
    42:  ("small", "petit", ("しょう", "しょうがしら"), ("小", "⺌"), None),
    43:  ("lame", "boiteux", ("だいのまげあし", "おうにょう"), ("尢", "尣"), None),
    44:  ("corpse", "cadavre", ("しかばね", "かばね"), ("尸",), "tare"),
    45:  ("sprout", "pousse", ("てつ", "くさのめ"), ("屮",), None),
    46:  ("mountain", "montagne", ("やま", "やまへん"), ("山",), "hen"),
    47:  ("river", "rivière", ("かわ", "まがりがわ"), ("川", "巛"), None),
    48:  ("work", "travail", ("こう", "たくみ"), ("工",), None),
    49:  ("oneself", "soi-même", ("おのれ",), ("己",), None),
    50:  ("cloth", "tissu", ("はば", "はばへん"), ("巾",), "hen"),
    51:  ("dry", "sec", ("かん", "ほす"), ("干",), None),
    52:  ("short thread", "fil court", ("いとがしら",), ("幺",), None),
    53:  ("house on a cliff", "bâtiment", ("まだれ",), ("广",), "tare"),
    54:  ("long stride", "grand pas", ("えんにょう",), ("廴",), "nyou"),
    55:  ("two hands", "deux mains", ("にじゅうあし", "こまぬき"), ("廾",), "ashi"),
    56:  ("stake", "pieu", ("しきがまえ", "いぐるみ"), ("弋",), None),
    57:  ("bow", "arc", ("ゆみ", "ゆみへん"), ("弓",), "hen"),
    58:  ("pig's head", "tête de porc", ("けいがしら",), ("彐", "彑"), "kanmuri"),
    59:  ("hair, strokes", "poils, traits", ("さんづくり",), ("彡",), "tsukuri"),
    60:  ("step", "pas", ("ぎょうにんべん",), ("彳",), "hen"),
    61:  ("heart", "cœur", ("こころ", "りっしんべん", "したごころ"), ("心", "忄", "㣺"), "hen"),
    62:  ("halberd", "hallebarde", ("ほこ", "ほこづくり"), ("戈",), "tsukuri"),
    63:  ("door", "porte", ("と", "とだれ", "とかんむり"), ("戸", "戶"), "tare"),
    64:  ("hand", "main", ("て", "てへん"), ("手", "扌"), "hen"),
    65:  ("branch", "branche", ("し", "しにょう"), ("支",), None),
    66:  ("strike", "frapper", ("ぼくづくり", "のぶん"), ("攵", "攴"), "tsukuri"),
    67:  ("script", "écriture", ("ぶん", "ぶんにょう"), ("文",), None),
    68:  ("dipper", "louche", ("と", "とます"), ("斗",), "tsukuri"),
    69:  ("axe", "hache", ("おの", "おのづくり"), ("斤",), "tsukuri"),
    70:  ("direction", "direction", ("ほう", "ほうへん", "かたへん"), ("方",), "hen"),
    71:  ("not", "négation", ("なし", "むにょう"), ("无", "旡"), None),
    72:  ("sun, day", "soleil, jour", ("ひ", "ひへん", "にちへん"), ("日",), "hen"),
    73:  ("say", "dire", ("ひらび", "いわく"), ("曰",), None),
    74:  ("moon", "lune", ("つき", "つきへん"), ("月",), "hen"),
    75:  ("tree", "arbre", ("き", "きへん"), ("木",), "hen"),
    76:  ("lack, yawn", "manque, bâillement", ("あくび", "かける"), ("欠",), "tsukuri"),
    77:  ("stop", "arrêt", ("とめる", "とめへん"), ("止",), None),
    78:  ("death, bones", "mort, ossements", ("がつへん", "かばねへん", "いちたへん"), ("歹", "歺"), "hen"),
    79:  ("weapon", "arme", ("るまた", "ほこづくり"), ("殳",), "tsukuri"),
    80:  ("do not", "ne pas", ("なかれ", "はは"), ("毋",), None),
    81:  ("compare", "comparer", ("くらべる", "ならびひ"), ("比",), None),
    82:  ("fur", "poil", ("け",), ("毛",), None),
    83:  ("clan", "clan", ("うじ",), ("氏",), None),
    84:  ("steam", "vapeur", ("きがまえ",), ("气",), "kamae"),
    85:  ("water", "eau", ("みず", "さんずい", "したみず"), ("水", "氵", "氺"), "hen"),
    86:  ("fire", "feu", ("ひ", "ひへん", "れっか", "れんが"), ("火", "灬"), "hen"),
    87:  ("claw", "griffe", ("つめ", "つめかんむり"), ("爪", "爫"), "kanmuri"),
    88:  ("father", "père", ("ちち",), ("父",), None),
    89:  ("crossed lines", "lignes croisées", ("こう", "めめ"), ("爻",), None),
    90:  ("half tree trunk", "demi-tronc", ("しょうへん",), ("爿", "丬"), "hen"),
    91:  ("slice", "tranche", ("かた", "かたへん"), ("片",), "hen"),
    92:  ("fang", "croc", ("きば", "きばへん"), ("牙",), None),
    93:  ("cow", "bœuf", ("うし", "うしへん"), ("牛", "牜"), "hen"),
    94:  ("dog", "chien", ("いぬ", "けものへん"), ("犬", "犭"), "hen"),
    95:  ("profound", "obscur", ("げん",), ("玄",), None),
    96:  ("jade, king", "jade, roi", ("たま", "たまへん", "おうへん"), ("王", "玉"), "hen"),
    97:  ("melon", "melon", ("うり",), ("瓜",), None),
    98:  ("tile", "tuile", ("かわら",), ("瓦",), None),
    99:  ("sweet", "sucré", ("あまい", "かん"), ("甘",), None),
    100: ("life", "vie", ("うまれる", "いきる"), ("生",), None),
    101: ("use", "usage", ("もちいる",), ("用",), None),
    102: ("rice field", "rizière", ("た", "たへん"), ("田",), "hen"),
    103: ("bolt of cloth", "rouleau de tissu", ("ひき", "ひきへん"), ("疋", "⺪"), None),
    104: ("sickness", "maladie", ("やまいだれ",), ("疒",), "tare"),
    105: ("footsteps", "pas écartés", ("はつがしら",), ("癶",), "kanmuri"),
    106: ("white", "blanc", ("しろ",), ("白",), None),
    107: ("skin", "peau", ("けがわ", "ひのかわ"), ("皮",), None),
    108: ("dish", "plat", ("さら",), ("皿",), "ashi"),
    109: ("eye", "œil", ("め", "めへん"), ("目",), "hen"),
    110: ("spear", "lance", ("ほこ", "ほこへん"), ("矛",), "hen"),
    111: ("arrow", "flèche", ("や", "やへん"), ("矢",), "hen"),
    112: ("stone", "pierre", ("いし", "いしへん"), ("石",), "hen"),
    113: ("altar, spirit", "autel, esprit", ("しめす", "しめすへん", "ねへん"), ("示", "礻"), "hen"),
    114: ("track", "empreinte", ("ぐうのあし",), ("禸",), None),
    115: ("grain", "céréale", ("のぎ", "のぎへん"), ("禾",), "hen"),
    116: ("cave", "trou, grotte", ("あな", "あなかんむり"), ("穴",), "kanmuri"),
    117: ("stand", "debout", ("たつ", "たつへん"), ("立",), None),
    118: ("bamboo", "bambou", ("たけ", "たけかんむり"), ("竹", "⺮"), "kanmuri"),
    119: ("rice", "riz", ("こめ", "こめへん"), ("米",), "hen"),
    120: ("thread", "fil de soie", ("いと", "いとへん"), ("糸",), "hen"),
    121: ("jar", "jarre", ("ほとぎ", "ほとぎへん"), ("缶",), None),
    122: ("net", "filet", ("あみがしら", "あみめ", "よこめ"), ("罒", "网", "罓"), "kanmuri"),
    123: ("sheep", "mouton", ("ひつじ",), ("羊", "⺶"), None),
    124: ("feather", "plume", ("はね",), ("羽",), None),
    125: ("old", "vieux", ("おい", "おいかんむり"), ("老", "耂"), "kanmuri"),
    126: ("and, beard", "et, barbe", ("しこうして",), ("而",), None),
    127: ("plough", "charrue", ("らいすき", "すきへん"), ("耒",), "hen"),
    128: ("ear", "oreille", ("みみ", "みみへん"), ("耳",), "hen"),
    129: ("brush", "pinceau", ("ふでづくり", "いつ"), ("聿",), None),
    130: ("flesh", "chair", ("にく", "にくづき"), ("月", "肉"), "hen"),
    131: ("minister", "vassal", ("しん",), ("臣",), None),
    132: ("self", "soi", ("みずから",), ("自",), None),
    133: ("arrive", "arriver", ("いたる", "いたるへん"), ("至",), None),
    134: ("mortar", "mortier", ("うす",), ("臼",), None),
    135: ("tongue", "langue", ("した", "したへん"), ("舌",), None),
    136: ("opposition", "opposition", ("まいあし", "ます"), ("舛",), None),
    137: ("boat", "bateau", ("ふね", "ふねへん"), ("舟",), "hen"),
    138: ("stopping", "limite", ("こん", "ごんづくり", "うしとら"), ("艮",), None),
    139: ("colour", "couleur", ("いろ",), ("色",), None),
    140: ("grass", "herbe", ("くさかんむり", "くさ"), ("艹", "艸"), "kanmuri"),
    141: ("tiger", "tigre", ("とらがしら", "とらかんむり"), ("虍",), "tare"),
    142: ("insect", "insecte", ("むし", "むしへん"), ("虫",), "hen"),
    143: ("blood", "sang", ("ち",), ("血",), None),
    144: ("go, walk", "aller, marcher", ("ぎょう", "ぎょうがまえ", "ゆきがまえ"), ("行",), "kamae"),
    145: ("clothes", "vêtement", ("ころも", "ころもへん"), ("衣", "衤"), "hen"),
    146: ("cover, west", "couvrir, ouest", ("おおいかんむり", "にし"), ("西", "襾", "覀"), "kanmuri"),
    147: ("see", "voir", ("みる",), ("見",), "tsukuri"),
    148: ("horn", "corne", ("つの", "つのへん"), ("角",), "hen"),
    149: ("speech", "parole", ("げん", "ごんべん"), ("言",), "hen"),
    150: ("valley", "vallée", ("たに", "たにへん"), ("谷",), None),
    151: ("bean", "haricot", ("まめ", "まめへん"), ("豆",), None),
    152: ("pig", "cochon", ("いのこ", "ぶた"), ("豕",), None),
    153: ("badger, beast", "bête féroce", ("むじな", "むじなへん"), ("豸",), None),
    154: ("shell, money", "coquillage, argent", ("かい", "かいへん"), ("貝",), "hen"),
    155: ("red", "rouge", ("あか",), ("赤",), None),
    156: ("run", "courir", ("はしる", "そうにょう"), ("走",), "nyou"),
    157: ("foot", "pied", ("あし", "あしへん"), ("足", "⻊"), "hen"),
    158: ("body", "corps", ("み", "みへん"), ("身",), "hen"),
    159: ("cart, vehicle", "véhicule", ("くるま", "くるまへん"), ("車",), "hen"),
    160: ("bitter", "amer", ("からい", "しん"), ("辛",), None),
    161: ("dawn, dragon", "aube, dragon", ("しんのたつ",), ("辰",), None),
    162: ("walk", "marche", ("しんにょう", "しんにゅう"), ("辶", "辵"), "nyou"),
    163: ("city", "ville", ("おおざと",), ("阝", "邑"), "tsukuri"),
    164: ("wine, alcohol", "vin, alcool", ("とり", "とりへん", "ひよみのとり"), ("酉",), "hen"),
    165: ("distinguish", "distinguer", ("のごめ", "のごめへん"), ("釆",), None),
    166: ("village", "village", ("さと", "さとへん"), ("里",), None),
    167: ("metal, gold", "métal, or", ("かね", "かねへん"), ("金",), "hen"),
    168: ("long", "long", ("ながい",), ("長", "镸"), None),
    169: ("gate", "portail", ("もん", "もんがまえ"), ("門",), "kamae"),
    170: ("mound", "colline", ("こざとへん", "こざと"), ("阝", "阜"), "hen"),
    171: ("capture", "capturer", ("れいづくり",), ("隶",), "tsukuri"),
    172: ("short-tailed bird", "oiseau à queue courte", ("ふるとり",), ("隹",), "tsukuri"),
    173: ("rain", "pluie", ("あめ", "あめかんむり"), ("雨",), "kanmuri"),
    174: ("blue, green", "bleu, vert", ("あお",), ("青", "靑"), None),
    175: ("wrong", "négation", ("あらず", "ひ"), ("非",), None),
    176: ("face", "visage", ("めん",), ("面", "靣"), None),
    177: ("leather", "cuir", ("かわへん", "つくりがわ"), ("革",), "hen"),
    178: ("tanned leather", "cuir tanné", ("なめしがわ",), ("韋",), None),
    179: ("leek", "poireau", ("にら",), ("韭",), None),
    180: ("sound", "son", ("おと", "おとへん"), ("音",), None),
    181: ("head, page", "tête, page", ("おおがい",), ("頁",), "tsukuri"),
    182: ("wind", "vent", ("かぜ",), ("風",), None),
    183: ("fly", "voler", ("とぶ",), ("飛",), None),
    184: ("eat, food", "manger, nourriture", ("しょく", "しょくへん"), ("食", "飠"), "hen"),
    185: ("head, neck", "tête, cou", ("くび",), ("首",), None),
    186: ("fragrance", "parfum", ("かおり", "か"), ("香",), None),
    187: ("horse", "cheval", ("うま", "うまへん"), ("馬",), "hen"),
    188: ("bone", "os", ("ほね", "ほねへん"), ("骨",), "hen"),
    189: ("tall", "haut", ("たかい",), ("高",), None),
    190: ("long hair", "longs cheveux", ("かみがしら", "かみかんむり"), ("髟",), "kanmuri"),
    191: ("fight", "combat", ("とうがまえ", "たたかいがまえ"), ("鬥",), "kamae"),
    192: ("sacrificial wine", "vin sacrificiel", ("ちょう",), ("鬯",), None),
    193: ("cauldron", "chaudron", ("かなえ", "れき"), ("鬲",), None),
    194: ("ghost, demon", "démon", ("おに", "きにょう"), ("鬼",), None),
    195: ("fish", "poisson", ("うお", "うおへん", "さかな"), ("魚",), "hen"),
    196: ("bird", "oiseau", ("とり", "とりへん"), ("鳥", "鳬"), "tsukuri"),
    197: ("salt", "sel", ("しお", "ろ"), ("鹵",), None),
    198: ("deer", "cerf", ("しか",), ("鹿",), None),
    199: ("wheat", "blé", ("むぎ", "ばくにょう"), ("麦", "麥"), None),
    200: ("hemp", "chanvre", ("あさ", "あさかんむり"), ("麻",), None),
    201: ("yellow", "jaune", ("き",), ("黄", "黃"), None),
    202: ("millet", "millet", ("きび",), ("黍",), None),
    203: ("black", "noir", ("くろ",), ("黒", "黑"), None),
    204: ("embroidery", "broderie", ("ふつ", "ぬいとり"), ("黹",), None),
    205: ("frog", "grenouille", ("べん", "かえる"), ("黽",), None),
    206: ("tripod", "tripode", ("かなえ",), ("鼎",), None),
    207: ("drum", "tambour", ("つづみ",), ("鼓",), None),
    208: ("rat", "rat", ("ねずみ", "ねずみへん"), ("鼠", "鼡"), None),
    209: ("nose", "nez", ("はな", "はなへん"), ("鼻",), None),
    210: ("even", "égal", ("せい",), ("斉", "齊"), None),
    211: ("tooth", "dent", ("は", "はへん"), ("歯", "齒"), None),
    212: ("dragon", "dragon", ("りゅう", "たつ"), ("竜", "龍"), None),
    213: ("turtle", "tortue", ("かめ",), ("亀", "龜"), None),
    214: ("flute", "flûte", ("やく", "ふえ"), ("龠",), None),
}
